version: 2

updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 3

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
