name: Test

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Elixir ${{matrix.elixir}} / OTP ${{matrix.otp}}
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        include:
          - elixir: '1.11'
            otp: '23'
          - elixir: '1.10'
            otp: '22'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Restore deps cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}

    - name: Restore _build cache
      uses: actions/cache@v2
      with:
        path: _build
        key: ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}

    - name: Install hex
      run: mix local.hex --force

    - name: Install rebar
      run: mix local.rebar --force

    - name: Install package dependencies
      run: mix deps.get

    - name: Remove compiled application files
      run: mix clean

    - name: Compile dependencies
      run: mix compile

    - name: Run unit tests
      run: mix test