name: Test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Elixir ${{matrix.elixir}} / OTP ${{matrix.otp}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - elixir: '1.14'
            otp: '25'
          - elixir: '1.15'
            otp: '25'
          - elixir: '1.16'
            otp: '26'
          - elixir: '1.17'
            otp: '27'
          - elixir: '1.18'
            otp: '27'
            lint: true

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Restore deps cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}

    - name: Restore _build cache
      uses: actions/cache@v4
      with:
        path: _build
        key: ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}

    - name: Install hex
      run: mix local.hex --force

    - name: Install rebar
      run: mix local.rebar --force

    - name: Install package dependencies
      run: mix deps.get

    - name: Validate format
      run: mix format --check-formatted
      if: ${{ matrix.lint }}

    - name: Remove compiled application files
      run: mix clean

    - name: Compile dependencies
      run: mix compile

    - name: Compile with warnings as errors
      run: mix compile --warnings-as-errors
      if: ${{ matrix.lint }}

    - name: Run unit tests
      run: mix test

    - name: Build docs (validate build)
      run: MIX_ENV=docs mix docs
      if: ${{ matrix.lint }}
